# Generated by Django 2.2.9 on 2020-05-18 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default='huyomoyo'),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='cats', unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='Kofa', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Group'),
        ),
    ]
